/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerPosRouteImport } from './routes/seller.pos'
import { Route as SellerMySalesRouteImport } from './routes/seller.my-sales'
import { Route as SellerLoginRouteImport } from './routes/seller.login'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerSalesHistoryRouteImport } from './routes/owner.sales-history'
import { Route as OwnerProductsRouteImport } from './routes/owner.products'
import { Route as OwnerLoginRouteImport } from './routes/owner.login'
import { Route as OwnerDashboardRouteImport } from './routes/owner.dashboard'
import { Route as OwnerCategoriesRouteImport } from './routes/owner.categories'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerPosRoute = SellerPosRouteImport.update({
  id: '/seller/pos',
  path: '/seller/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerMySalesRoute = SellerMySalesRouteImport.update({
  id: '/seller/my-sales',
  path: '/seller/my-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerLoginRoute = SellerLoginRouteImport.update({
  id: '/seller/login',
  path: '/seller/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSalesHistoryRoute = OwnerSalesHistoryRouteImport.update({
  id: '/owner/sales-history',
  path: '/owner/sales-history',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerProductsRoute = OwnerProductsRouteImport.update({
  id: '/owner/products',
  path: '/owner/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerCategoriesRoute = OwnerCategoriesRouteImport.update({
  id: '/owner/categories',
  path: '/owner/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner/categories': typeof OwnerCategoriesRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/sales-history': typeof OwnerSalesHistoryRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/my-sales': typeof SellerMySalesRoute
  '/seller/pos': typeof SellerPosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner/categories': typeof OwnerCategoriesRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/sales-history': typeof OwnerSalesHistoryRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/my-sales': typeof SellerMySalesRoute
  '/seller/pos': typeof SellerPosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner/categories': typeof OwnerCategoriesRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/sales-history': typeof OwnerSalesHistoryRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/my-sales': typeof SellerMySalesRoute
  '/seller/pos': typeof SellerPosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner/categories'
    | '/owner/dashboard'
    | '/owner/login'
    | '/owner/products'
    | '/owner/sales-history'
    | '/owner/settings'
    | '/seller/login'
    | '/seller/my-sales'
    | '/seller/pos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner/categories'
    | '/owner/dashboard'
    | '/owner/login'
    | '/owner/products'
    | '/owner/sales-history'
    | '/owner/settings'
    | '/seller/login'
    | '/seller/my-sales'
    | '/seller/pos'
  id:
    | '__root__'
    | '/'
    | '/owner/categories'
    | '/owner/dashboard'
    | '/owner/login'
    | '/owner/products'
    | '/owner/sales-history'
    | '/owner/settings'
    | '/seller/login'
    | '/seller/my-sales'
    | '/seller/pos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerCategoriesRoute: typeof OwnerCategoriesRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  OwnerProductsRoute: typeof OwnerProductsRoute
  OwnerSalesHistoryRoute: typeof OwnerSalesHistoryRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  SellerLoginRoute: typeof SellerLoginRoute
  SellerMySalesRoute: typeof SellerMySalesRoute
  SellerPosRoute: typeof SellerPosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/pos': {
      id: '/seller/pos'
      path: '/seller/pos'
      fullPath: '/seller/pos'
      preLoaderRoute: typeof SellerPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/my-sales': {
      id: '/seller/my-sales'
      path: '/seller/my-sales'
      fullPath: '/seller/my-sales'
      preLoaderRoute: typeof SellerMySalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/login': {
      id: '/seller/login'
      path: '/seller/login'
      fullPath: '/seller/login'
      preLoaderRoute: typeof SellerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/sales-history': {
      id: '/owner/sales-history'
      path: '/owner/sales-history'
      fullPath: '/owner/sales-history'
      preLoaderRoute: typeof OwnerSalesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/products': {
      id: '/owner/products'
      path: '/owner/products'
      fullPath: '/owner/products'
      preLoaderRoute: typeof OwnerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/categories': {
      id: '/owner/categories'
      path: '/owner/categories'
      fullPath: '/owner/categories'
      preLoaderRoute: typeof OwnerCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerCategoriesRoute: OwnerCategoriesRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  OwnerProductsRoute: OwnerProductsRoute,
  OwnerSalesHistoryRoute: OwnerSalesHistoryRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  SellerLoginRoute: SellerLoginRoute,
  SellerMySalesRoute: SellerMySalesRoute,
  SellerPosRoute: SellerPosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
